[[rules]]
    description = "Generic_Password"
    regex = '''(?i)[\"]*Password[\"\s]*:[\s\"i\']*(?-i)([0-9a-zA-Z!\$\@\%]{4,60})[\s\"\'i,]*$'''
    tags = ["password"]

[[rules]]
    description = "clientSecret"
    regex = '''(?i)[\"]*clientSecret[\"]*:[\s\"i\']*(?-i)([0-9a-zA-Z!\$\-]{4,60})[\s\"\'i,]*$'''
    tags = ["password"]

[[rules]]
    description = "Bearer"
    regex = '''(?i)[\"]*bearer[\"]*[\s\"i\']*(?-i)([0-9a-zA-Zi\-\.\_]+)[\s\"\'i,]*'''
    tags = ["password"]

[allowlist]
	description = "Allowlisted files"
	paths = ['''.git''','''node_modules/amazon-cognito-identity-js''','''node_modules/pg''','''node_modules/node-redshift''','''node_modules/pg-protocol''','''node_modules/public-encrypt''','''node_modules/http-signature''','''node_modules/chance''','''node_modules/lazystream''','''node_modules/serverless''','''node_modules/@serverless''','''README.md''','''node_modules/aws-sdk''','''serverless/skpi-loadToElastic/boto3/examples''' , '''serverless/skpi-websocketElastic/botocore''' , '''serverless/skpi-websocketElastic/boto3/examples''']


